-- Migração: adicionar suporte a exceções genéricas na tabela existente
-- Execute se a tabela EXCECAO_SEMESTRE já foi criada anteriormente.

ALTER TABLE EXCECAO_SEMESTRE ADD (
    DESCRICAO_LIVRE      VARCHAR2(1000),
    PARAMETROS_JSON      CLOB,
    STATUS_INTERPRETACAO VARCHAR2(20) DEFAULT 'OK'
);

ALTER TABLE EXCECAO_SEMESTRE
    ADD CONSTRAINT CHK_STATUS_INTERP
        CHECK (STATUS_INTERPRETACAO IN ('OK', 'PENDENTE_REVISAO', 'ERRO'));

-- Ampliar o CHECK de TIPO para incluir GENERICA
ALTER TABLE EXCECAO_SEMESTRE DROP CONSTRAINT CHK_EXCECAO_TIPO;
ALTER TABLE EXCECAO_SEMESTRE
    ADD CONSTRAINT CHK_EXCECAO_TIPO
        CHECK (TIPO IN ('SALA_INTERDITADA', 'COMPARTILHAMENTO', 'CAPACIDADE_SALA', 'GENERICA'));

COMMENT ON COLUMN EXCECAO_SEMESTRE.DESCRICAO_LIVRE      IS 'Texto livre original (input humano para tipo GENERICA)';
COMMENT ON COLUMN EXCECAO_SEMESTRE.PARAMETROS_JSON      IS 'Regra estruturada em JSON gerada pela IA ou manualmente';
COMMENT ON COLUMN EXCECAO_SEMESTRE.STATUS_INTERPRETACAO IS 'OK=aplicada | PENDENTE_REVISAO=IA nao teve certeza | ERRO=falha';
